backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        if(Yii::$app->user->can('manage-site')){
        return $this->render('index');
        }else{
            throw new ForbiddenHttpException;
        }
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use app\models\Categories;
use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use app\models\Pages;
use app\models\Posts;
use app\models\Videos;
use app\models\Photos;
use yii\web\NotFoundHttpException;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\web\HttpException;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $post = new Posts;
        $data = $post->find()->all();
        $category = new Categories;
        $head = $category->find()->all();
        $dataProvider = new ActiveDataProvider([
            'query'=>Posts::find(),
            'sort'=>[
                'defaultOrder'=>['create_date'=>SORT_DESC]
            ],
            'pagination'=>[
                'pageSize'=>10,
            ],
        ]);
        echo $this->render('index', array(
            'dataProvider' => $dataProvider,
            'head' => $head,
            'pages'=>$dataProvider->pagination
        ));
    }
    public function actionVideo(){
        $video = new Videos;
        $dataProvider = new ActiveDataProvider([
            'query'=>Videos::find(),
            'sort'=>[
                'defaultOrder'=>['id'=>SORT_DESC]
            ],
            'pagination'=>[
                'pageSize'=>5,
            ],
        ]);
        return $this->render('video',array(
            'dataProvider' => $dataProvider
        ));
    }
    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $page = new Pages();
        $data = $page->find()->all();
        return $this->render('contact',[
            'data'=>$data,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        $page = new Pages();
        $data = $page->find()->all();
        return $this->render('about',[
            'data'=>$data,
            ]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
    public function actionRead($id)
    {
        $post = $this->findModel($id);
        return $this->render('read', [
            'post' => $post,
        ]);
    }
    protected function findModel($id)
    {
        if (($model = Posts::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    public function actionImage(){
        $dataProvider = new ActiveDataProvider([
            'query'=>Photos::find(),
            'sort'=>[
                'defaultOrder'=>['id'=>SORT_DESC]
            ],
            'pagination'=>[
                'pageSize'=>10,
            ],
        ]);
        return $this->render('image',array(
            'dataProvider' => $dataProvider,
            'pages' => $dataProvider->pagination,
        ));
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
?>
<div class="site-about">
    <?php foreach ($data as $post):?>
        <?php if($post->id==1){ ?>
    <h1><?= Html::encode($post->name) ?></h1>

        <p><?php echo $post->content; ?></p>

  <?php }?>
    <?php endforeach; ?>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
?>
<div class="site-contact">

    <?php foreach ($data as $post):?>
        <?php if($post->id==2){ ?>
            <h1><?= Html::encode($post->name) ?></h1>

            <p><?php echo $post->content; ?></p>

        <?php }?>
    <?php endforeach; ?>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>


</div>

frontend/views/site/image.php
<?php
use yii\widgets\LinkPager;
/**
 * Created by PhpStorm.
 * User: Yurii
 * Date: 1/7/2016
 * Time: 9:12 PM
 */
$this->title = 'Photos';
$data = $dataProvider->getModels();
if(empty($data)){
    echo "<div class=\"alert alert-info\" role=\"alert\"><h1>No photos yet</h1></div>";
} ?>
<div class="photos">

    <?php   $items = array();
foreach ($data as $file):
    array_push($items,
        [
            'url' => $file->path,
            'src' => $file->path,
            'options' => array('title' => $file->title)
        ]
    );
endforeach;
?>
<?= dosamigos\gallery\Gallery::widget(['items' => $items]);?>

</div>
<?= LinkPager::widget([
    'pagination' => $pages,
]); ?>

frontend/views/site/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;
/* @var $this yii\web\View */

$this->title = 'diamond memoirs';
?>
<div class="clearfix"></div>
<ul class="nav nav-pills nav-stacked" id="categories">
    <li role="presentation"><h2>Categories</h2></li>
    <li role="presentation" id="All" class="active"><?= Html::a('All',$url='#'); ?></li>
    <?php foreach($head as $category): ?>
        <li role="presentation" id="<?=$category->id?>"><?= Html::a($category->name,$url='#'); ?></li>
    <?php endforeach; ?>
</ul>
<div class="posts">


<!--    --><?php

    $data = $dataProvider->getModels();
    if(empty($data)){
        echo "<div class=\"alert alert-info\" role=\"alert\"><h1>No posts yet</h1></div>";
    }
    foreach($data as $model):
    ?>

    <div class="category<?=$model->category_id?>">
        <div class="blog-post" >
            <h2 class="blog-post-title"><?= Html::a($model->title, array('site/read', 'id'=>$model->id)); ?></h2>
            <p class="blog-post-meta"><?= Html::encode(date('d F Y',$model->create_date)); ?></p>
            <br>
            <div class="intro">
                <?php
                $text = preg_replace( "/<img.*>/","", $model->text );
                if(strlen($text)<=255){
                    echo Html::decode($text);
                } else {
                    echo Html::decode(substr($text, 0, 255)) . "...";
                    echo Html::a('Read more',array('site/read', 'id'=>$model->id));
                }
                echo '</div>';
                if($model->image != "")
                    echo Html::img($model->image,['href'=>array('site/read', 'id'=>$model->id)])
                ?>

            </div>
        </div>

  <?php  endforeach;?>
        <?= LinkPager::widget([
            'pagination' => $pages,
        ]); ?>

    </div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/read.php
<?php
/**
 * Created by PhpStorm.
 * User: Yurii
 * Date: 12/30/2015
 * Time: 5:13 PM
 */
use yii\helpers\Html;
use yii\helpers\Url; ?>
<?php $this->title = $post->title ?>
<div class="blog-post" >
    <h2 class="blog-post-title"><?php echo $post->title; ?></h2>
   <p class="blog-post-meta"> <?php echo date('d F Y',$post->create_date); ?></p>
<div class="intro"><p><?php echo $post->text; ?></p></div>
</div>
<div class="share">
    <h4>Share this:</h4>
<span class='st_facebook_large' displayText='Facebook'></span>
<span class='st_twitter_large' displayText='Tweet'></span>
<span class='st_pinterest_large' displayText='Pinterest'></span>
<span class='st_vkontakte_large' displayText='Vkontakte'></span>
<span class='st_tumblr_large' displayText='Tumblr'></span>
<span class='st_email_large' displayText='Email'></span>
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "75339d0b-7b4f-46fb-848f-a58570f4dddb", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email') ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username') ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/video.php
<?php
use yii\widgets\ListView;
/**
 * Created by PhpStorm.
 * User: Yurii
 * Date: 1/7/2016
 * Time: 11:41 PM
 */
$this->title = 'Videos';
$videos = $dataProvider->getModels();
if(empty($videos)){
    echo "<div class=\"alert alert-info\" role=\"alert\"><h1>No videos yet</h1></div>";
}
echo "<div class='videos' >";
foreach ($videos as $video): ?>
    <h2><?=$video->name?></h2>
    <?=$video->code?>
<?php endforeach; ?>
</div>

frontend/views/site/view.php

<?php
use yii\helpers\Html;

?>
<div class="category<?=$model->category_id?>">
         <div class="blog-post" >
            <h2 class="blog-post-title"><?= Html::a($model->title, array('site/read', 'id'=>$model->id)); ?></h2>
<p class="blog-post-meta"><?= Html::encode(date('d F Y',$model->create_date)); ?></p>
<br>
<div class="intro">
    <?php
    $text = preg_replace( "/<img.*>/","", $model->text );
    if(strlen($text)<=255){
        echo Html::decode($text);
    } else {
        echo Html::decode(substr($text, 0, 255)) . "...";
        echo Html::a('Read more',array('site/read', 'id'=>$model->id));
    }
    echo '</div>';
    if($model->image != "")
        echo Html::img($model->image,['href'=>array('site/read', 'id'=>$model->id)])
    ?>

</div>
</div>